#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Tue Apr 02 23:06:58 EEST 2019
apiSecret=e65454fc9aed656f907f8d8fa6d8a93fa0ea32fa4064f8987d06330dd02f7cb0
